"""Repository and file operations required by authored records."""
from contextlib import AbstractContextManager
from pathlib import Path
from typing import Protocol


class RecordWriter(Protocol):
    def root(self, path: str | Path) -> str: ...
    def create(self, root: Path) -> None: ...
    def export(self, root: str, path: str, revision: str, target: Path) -> str: ...
    def validate_path(self, root: str, path: str) -> None: ...
    def lock(self, root: str) -> AbstractContextManager[None]: ...
    def read(self, root: str, path: str, revision: str) -> str: ...
    def log(self, root: str, path: str | None, revision: str) -> list[dict]: ...
    def find(self, root: str, intent: dict) -> str | None: ...
    def commit(self, root: str, intent: dict, body: str) -> str: ...
