"""What the canvas kernel needs from the rest of Fleet, and from its own persistence."""
from __future__ import annotations

from contextlib import AbstractContextManager
from dataclasses import dataclass
from typing import Any, Callable, Protocol


class CanvasRepository(Protocol):
    def load(self, space: str) -> dict[str, dict[str, dict]]: ...
    def save(self, space: str, kind: str, identity: str, record: dict | None, actor: str) -> None: ...
    def present(self, space: str, kind: str, identity: str, record: dict) -> None: ...
    def save_version(self, space: str, kind: str, identity: str, version: int, record: dict) -> None: ...
    def versions(self, space: str, kind: str, identity: str) -> list[dict]: ...
    def append_event(self, space: str, event: dict) -> int: ...
    def events(self, space: str, *, after: int = 0, limit: int | None = None) -> list[dict]: ...
    def last_event(self, space: str) -> int: ...
    def op_result(self, op_id: str) -> dict | None: ...
    def remember_op(self, op_id: str, space: str, op: str, result: dict) -> None: ...
    def layout(self, space: str, person: str) -> dict[str, dict]: ...
    def set_layout(self, space: str, person: str, object_ref: str, props: dict | None) -> None: ...
    def spaces(self) -> list[str]: ...


class WorkPort(Protocol):
    def add(self, *, project: str, title: str, goal: str, actor: str, kind: str = "task",
            parent: str | None = None, **fields) -> Any: ...
    def get(self, identity: str) -> Any: ...
    def list(self, *, project: str | None = None) -> list: ...
    def set(self, identity: str, *, actor: str, **changes) -> Any: ...
    def move(self, identity: str, *, parent: str | None, actor: str) -> Any: ...
    def criteria_by_item(self) -> dict[str, list]: ...
    def add_criterion(self, identity: str, *, text: str, verification: str, actor: str, **fields) -> Any: ...
    def remove_criterion(self, identity: str, *, actor: str) -> None: ...
    def relate(self, from_item: str, to_item: str, *, actor: str, type: str = "depends-on") -> Any: ...
    def unrelate(self, from_item: str, to_item: str, *, actor: str, type: str = "depends-on") -> None: ...
    def relations_by_item(self) -> dict[str, list]: ...


class AttentionPort(Protocol):
    def raise_item(self, **fields) -> Any: ...
    def resolve(self, item_id: str, *, details: str, actor: str) -> Any: ...
    def reopen(self, item_id: str, *, actor: str) -> Any: ...
    def get(self, item_id: str) -> Any: ...
    def list(self, *, project: str | None = None, state: str | None = None, owner: str | None = None) -> list: ...


class DecisionsPort(Protocol):
    def answer(self, identity: str, answer: str, *, actor: str, next_step: str | None = None) -> Any: ...
    def list(self) -> list: ...


class GuidancePort(Protocol):
    def guidance(self, project: str, epic: str | None = None, *, number: int | None = None) -> Any: ...
    def space_guidance(self, project: str) -> dict | None: ...
    def write_space_guidance(self, project: str, value: dict, *, actor: str,
                             base: int | None = None) -> dict: ...


@dataclass
class Ports:
    """Facades bound to the same transaction as the canvas records, plus read-only run lookups."""
    work: WorkPort
    attention: AttentionPort
    decisions: DecisionsPort
    run: Callable[[str], Any | None]
    run_attention: Callable[[dict], list]
    guidance: GuidancePort
    transaction: Callable[[], AbstractContextManager] | None = None
    # What the host last streamed about a job (steps, recent events); None where no live runtime is attached.
    live_job: Callable[[str, str], dict | None] | None = None
