"""Mechanical persistence port."""

from __future__ import annotations

from datetime import datetime
from typing import ContextManager, Protocol

from ..domain import AttentionReply, AttentionItem, ImportedAction


class AttentionRepository(Protocol):
    def transaction(self) -> ContextManager["AttentionRepository"]: ...
    def get(self, item_id: str) -> AttentionItem: ...
    def resolving_actor(self, item_id: str) -> str | None: ...
    def find(self, source: str, source_reference: str) -> AttentionItem | None: ...
    def list(self, *, project: str | None = None, owner: str | None = None,
             source: str | None = None, subjects: set[str] | None = None,
             source_reference: str | None = None) -> list[AttentionItem]: ...
    def snooze_ends(self) -> list[datetime]: ...
    def save(self, item: AttentionItem, previous: str | None, actor: str) -> None: ...
    def save_reply(self, item: AttentionItem, reply: AttentionReply) -> None: ...
    def save_owner(self, item: AttentionItem, previous: str, actor: str) -> None: ...
    def imported_action(self, reference: str) -> ImportedAction | None: ...
