"""Mechanical persistence port."""

from typing import ContextManager, Protocol

from ..domain import AttentionReply, AttentionItem, ImportedAction


class AttentionRepository(Protocol):
    def transaction(self) -> ContextManager["AttentionRepository"]: ...
    def get(self, item_id: str) -> AttentionItem: ...
    def resolving_actor(self, item_id: str) -> str | None: ...
    def find(self, source: str, source_reference: str) -> AttentionItem | None: ...
    def list(self) -> list[AttentionItem]: ...
    def save(self, item: AttentionItem, previous: str | None, actor: str) -> None: ...
    def save_reply(self, item: AttentionItem, reply: AttentionReply) -> None: ...
    def save_owner(self, item: AttentionItem, previous: str, actor: str) -> None: ...
    def imported_action(self, reference: str) -> ImportedAction | None: ...
