from typing import Callable, ContextManager, Protocol

from fleet.modules.attention import AttentionFacade

from ..domain import Action, Delivery, Run

InputSender = Callable[[Run, Delivery], str | None]


class ExecutionRepository(Protocol):
    attention: AttentionFacade
    def transaction(self) -> ContextManager["ExecutionRepository"]: ...
    def find(self, host: str, job: str) -> Run | None: ...
    def actions(self) -> list[Action]: ...
    def runs(self) -> list[Run]: ...
    def save(self, action: Action, run: Run, actor: str) -> None: ...
    def update(self, run: Run, actor: str) -> None: ...
    def deliveries(self) -> list[Delivery]: ...
    def save_delivery(self, delivery: Delivery, actor: str) -> None: ...
