from typing import Callable, ContextManager, Protocol

from fleet.modules.attention import AttentionFacade
from fleet.modules.work import WorkFacade
from fleet.modules.workspace import WorkspaceFacade

from ..domain import Action, Claim, Delivery, Run
from .dtos import InputResult

InputSender = Callable[[Run, Delivery], InputResult]


class ExecutionRepository(Protocol):
    attention: AttentionFacade
    work: WorkFacade
    workspace: WorkspaceFacade

    def transaction(self) -> ContextManager["ExecutionRepository"]: ...
    def find(self, host: str, job: str) -> Run | None: ...
    def get_run(self, identity: str) -> Run: ...
    def get_action(self, identity: str) -> Action: ...
    def actions(self) -> list[Action]: ...
    def runs(self) -> list[Run]: ...
    def save(self, action: Action, run: Run, actor: str) -> None: ...
    def update(self, run: Run, actor: str) -> None: ...
    def deliveries(self) -> list[Delivery]: ...
    def save_delivery(self, delivery: Delivery, actor: str) -> None: ...
    def claims(self) -> list[Claim]: ...
    def save_action(self, action: Action, actor: str) -> None: ...
    def save_run(self, run: Run, actor: str) -> None: ...
    def save_claim(self, claim: Claim, actor: str) -> None: ...
    def release_claim(self, run: str, actor: str) -> None: ...
    def request(self, key: str, fingerprint: str) -> Run | None: ...
    def save_request(self, key: str, fingerprint: str, run: str, actor: str) -> None: ...
