from typing import ContextManager, Protocol

from ..domain import Action, Run


class ExecutionRepository(Protocol):
    def transaction(self) -> ContextManager["ExecutionRepository"]: ...
    def find(self, host: str, job: str) -> Run | None: ...
    def actions(self) -> list[Action]: ...
    def runs(self) -> list[Run]: ...
    def save(self, action: Action, run: Run, actor: str) -> None: ...
